.TH hvn-init 1 2020-06-25 HeylelOS
.SH NAME
.PP
Initialize a module.
.SH SYNOPSIS
.PP
hvn-init [-S sources] [-e extension] targets...
.SH DESCRIPTION
.PP
Create a subdirectory for each target in sources. And creates a hello world if it is not considered a library, and the language is supported.
.SH OPTIONS
.PP
-S : Sources, where to create the modules, by default src.
.PP
-e : Extension used for hello worlds, by default .c.
.PP
targets : Names of the modules to create, a name prefixed with lib will be considered a library, else an executable.
.SH AUTHOR
.PP
Valentin Debon (valentin.debon@heylelos.org)
.SH SEE ALSO
.PP
hvn(1), hvn-cfgen(1), hvn-mkgen(1), hvn-mando(1), hvn-pkgen(1).
